#  This is a free for use and open source, most complete mobile application for nopCommerce platform based on Flutter and NopSuite front-end API for nopCommerce by NopAdvance LLP.
#  Copyright (C) 2022 - NopAdvance LLP
#
#  This program is free software: you can redistribute and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License.
#
#  This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
#  This program is forever free software: you can modify and/or redistribute. One cannot sell or relicense the source code it under the terms of the NopAdvance Public license terms.
#
#  You should have received a copy of the GNU General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.

name: nopsuite
description: Open source mobile application for nopCommerce platform based on Flutter and NopSuite Front-end API for nopCommerce

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  http: ^0.13.5
  shared_preferences: ^2.0.17
  sqflite: ^2.2.4+1
  path_provider:
  permission_handler: 10.2.0
  url_launcher: ^6.1.8
  intl: ^0.18.0
  flutter_typeahead: ^4.3.2
  file_picker: ^4.6.1
  pdf: ^3.9.0
  open_file: 3.2.1
  flutter_inappwebview: ^5.7.2+3
  lazy_load_scrollview: 1.3.0
  share_plus: ^4.5.3
  printing: ^5.10.1
  connectivity: ^3.0.6
  ionicons: ^0.2.2
  simple_html_css: ^4.0.0
  flutter_widget_from_html: ^0.10.0
  cached_network_image: ^3.2.3
  localstorage: 4.0.0+1
  carousel_slider: ^4.2.1
  provider:
  flutter_svg: ^2.0.5
  youtube_player_flutter: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/Flexo/
    - assets/Common/
    - assets/Icons/
    - assets/Images/

  fonts:
    - family: Arimo
      fonts:
        - asset: fonts/Arimo-Bold.ttf
        - asset: fonts/Arimo-BoldItalic.ttf
        - asset: fonts/Arimo-Italic.ttf
        - asset: fonts/Arimo-Medium.ttf
        - asset: fonts/Arimo-MediumItalic.ttf
        - asset: fonts/Arimo-Regular.ttf
        - asset: fonts/Arimo-SemiBoldItalic.ttf
        - asset: fonts/Arimo-SemiBold.ttf
          style: italic

    - family: OpenSans
      fonts:
          - asset: fonts/OpenSans/OpenSans-Bold.ttf
          - asset: fonts/OpenSans/OpenSans-BoldItalic.ttf
          - asset: fonts/OpenSans/OpenSans-ExtraBold.ttf
          - asset: fonts/OpenSans/OpenSans-ExtraBoldItalic.ttf
          - asset: fonts/OpenSans/OpenSans-Italic.ttf
          - asset: fonts/OpenSans/OpenSans-Light.ttf
          - asset: fonts/OpenSans/OpenSans-LightItalic.ttf
          - asset: fonts/OpenSans/OpenSans-Medium.ttf
          - asset: fonts/OpenSans/OpenSans-MediumItalic.ttf
          - asset: fonts/OpenSans/OpenSans-Regular.ttf
          - asset: fonts/OpenSans/OpenSans-SemiBold.ttf
          - asset: fonts/OpenSans/OpenSans-SemiBoldItalic.ttf
            style: italic
            weight: 500

    - family: MontSerrat
      fonts:
          - asset: fonts/montSerrat/Montserrat-Black.ttf
          - asset: fonts/montSerrat/Montserrat-BlackItalic.ttf
          - asset: fonts/montSerrat/Montserrat-Bold.ttf
          - asset: fonts/montSerrat/Montserrat-BoldItalic.ttf
          - asset: fonts/montSerrat/Montserrat-ExtraBold.ttf
          - asset: fonts/montSerrat/Montserrat-ExtraBoldItalic.ttf
          - asset: fonts/montSerrat/Montserrat-ExtraLight.ttf
          - asset: fonts/montSerrat/Montserrat-ExtraLightItalic.ttf
          - asset: fonts/montSerrat/Montserrat-Italic.ttf
          - asset: fonts/montSerrat/Montserrat-Light.ttf
          - asset: fonts/montSerrat/Montserrat-LightItalic.ttf
          - asset: fonts/montSerrat/Montserrat-Medium.ttf
          - asset: fonts/montSerrat/Montserrat-MediumItalic.ttf
          - asset: fonts/montSerrat/Montserrat-Regular.ttf
          - asset: fonts/montSerrat/Montserrat-SemiBold.ttf
          - asset: fonts/montSerrat/Montserrat-SemiBoldItalic.ttf
          - asset: fonts/montSerrat/Montserrat-Thin.ttf
          - asset: fonts/montSerrat/Montserrat-ThinItalic.ttf
            style: italic
            weight: 500

